### ISSUE TITLE
typescript support

### ISSUE THREAD

**Issue by Vi-brance** [bhsd-harry/wikiparser-node#3]
虽然已经有一部分声明文件，但是在编译typescript项目时还是会因为有些部分没有对应的声明文件而报错

**Comment by bhsd-harry** [comment]
正在整体修改为typescript，但预计会花较长的时间。

**Comment by Vi-brance** [comment]
如果只是单纯转ts的话我也许可以提供部分帮助

**Comment by bhsd-harry** [comment]
> 如果只是单纯转ts的话我也许可以提供部分帮助

那太感谢了！我后天应该有时间先push到当前进度。

**Comment by bhsd-harry** [comment]
@Vi-brance 抱歉，我才想起来转typescript的进度在另一个[repo](https://github.com/bhsd-harry/wikiparser-typescript)里，请移步。

**Comment by bhsd-harry** [comment]
702a79860692631ca1fcda07b52fd7f76dbb3c5c
