### ISSUE TITLE
TypeScript模块编译错误

### ISSUE THREAD

**Issue by Vi-brance** [bhsd-harry/wikiparser-node#31]
导入此模块后编译出现以下类型的错误：

```sh
node_modules/wikiparser-node/dist/lib/node.d.ts:129:35 - error TS2304: Cannot find name 'AstEventData'.

129     dispatchEvent(e: Event, data: AstEventData): void;
                                      ~~~~~~~~~~~~
```

查询后发现模块没有包含 `typings` 目录下的所有声明文件。

**Comment by bhsd-harry** [comment]
@Vi-brance 我预想的是这里的`AstEventData`会自动理解成`any`？

**Comment by bhsd-harry** [comment]
建议在`tsconfig.json`里加上一条`"skipLibCheck": true`再试试。

**Comment by bhsd-harry** [comment]
@Vi-brance 已发布[wikiparser-node@1.7.1](https://www.npmjs.com/package/wikiparser-node/v/1.7.1)。
