### ISSUE TITLE
以CRLF（`\r\n`）分行的文本中`Table` 语法无法识别

### ISSUE THREAD

**Issue by Vi-brance** [bhsd-harry/wikiparser-node#33]
在以CRLF（`\r\n`）分行的文本中无法正确解析 `Table` 语法，换成LF（`\n`）分行后解析结果正确。

**Comment by Vi-brance** [comment]
问题仍存在，这是被识别为 `AstText` 的文本

```
{|\r\n! table example\r\n|-\r\n| table end\r\n|}\r\n\r\n
```

**Comment by bhsd-harry** [comment]
> 问题仍存在，这是被识别为 `AstText` 的文本
> 
> ```
> {|\r\n! table example\r\n|-\r\n| table end\r\n|}\r\n\r\n
> ```

无法复现。请升级到 v1.8.0。

**Comment by Vi-brance** [comment]
> > 问题仍存在，这是被识别为 `AstText` 的文本
> > ```
> > {|\r\n! table example\r\n|-\r\n| table end\r\n|}\r\n\r\n
> > ```
> 
> 无法复现。请升级到 v1.8.0。

不好意思，更新失效了，重装模块后问题解决，感谢。
