### ISSUE TITLE
关于如何全局修改 `config` 对象的疑问

### ISSUE THREAD

**Issue by Vi-brance** [bhsd-harry/wikiparser-node#35]
我希望能自定义 `config` 的配置内容，但是每次调用 `parse()` 函数时都需要传入这个配置信息较为繁琐，我想直接修改 `Parser` 中的`config` 成员使其能在之后的解析中都默认使用这个配置。

我尝试通过以下代码实现上述功能，代码如下：
```ts
import Parser, * as wikiparserNode from 'wikiparser-node';
const MwParser: Parser = wikiparserNode;
MwParser.config = xxx;
MwParser.parse(wikitext);
```
但在调试过程中程序进入 `parse` 函数后 `config` 的修改并没有被应用，请问有什么解决办法。

**Comment by bhsd-harry** [comment]
@Vi-brance 直接`import * as MwParser from 'wikiparser-node';`就能改了。

**Comment by Vi-brance** [comment]
我修改了导入方式但显示
```
TS2540: Cannot assign to 'config' because it is a read-only property.
```
调试时的 `MwParser` 对象结构为：
```
MwParser:
  conversionTable
  debugging
  default:
    parse
    normalizeTitle
    config
    ...
  ... 
```

静态检查时 `MwParser` 并没有 `default` 成员，但通过 `ts-expect-error` 跳过检查程序直接赋值可以正常执行。

可能最好还是需要修改模块导出的结构以避免这种情况出现。

**Comment by bhsd-harry** [comment]
@Vi-brance 出于向后兼容的考虑我不会改动。另外你也可以试试`import MwParser = require('wikiparser-node');`。

**Comment by Vi-brance** [comment]
> @Vi-brance 出于向后兼容的考虑我不会改动。另外你也可以试试`import MwParser = require('wikiparser-node');`。

用 `require` 导入可以正常识别 `config` 成员了。
