### ISSUE TITLE
More functionality

### ISSUE THREAD

**Issue by bhsd-harry** [bhsd-harry/wikiparser-node#4]
Suggestions from @lovelyCARDINAL (rephrased)

- [x] Manually set unidirectional conversions and redirections.
- [x] Allow regular expressions in selectors.
- [x] Create `AstRange` class (8c71f01972752197b920db36802fe8732f430fb1).

**Comment by bhsd-harry** [comment]
新功能用法示例：

```js
Parser = require('wikiparser-node');

// 1. 设置单向转换
Parser.conversionTable.set('簡', '简');
Parser.conversionTable.set('體', '体');
assert(Parser.normalizeTitle('簡體').title === '简体');
assert(Boolean(Parser.parse('[[簡體]]').querySelector('#简体')));

// 2. 设置重定向
Parser.redirects.set('正体', '繁体');
assert(Parser.normalizeTitle('正体').title === '繁体');
assert(Boolean(Parser.parse('[[正体]]').querySelector('#繁体')));

// 3. 正则选择器
assert(Boolean(Parser.parse('[[簡體]]').querySelector(':regex(name, /[簡简][體体]/)')));
```

**Comment by lovelyCARDINAL** [comment]
conversionTable和redirects可以加一个导入json的功能不

另外我觉得redirects优先级应该比conversionTable高

**Comment by bhsd-harry** [comment]
> conversionTable和redirects可以加一个导入json的功能不
> 
> 另外我觉得redirects优先级应该比conversionTable高

现在conversionTable和redirects均可直接以entries的格式写入config文件，例如：

```jsonc
{
  // 其他规定的设置项
  "conversionTable": [
    ["A", "B"]
  ],
  "redirects": [
    ["C", "D"]
  ]
}
```

关于优先级，现在会先检查redirects，失败时执行autoConvert并再次检查redirects。

**Comment by lovelyCARDINAL** [comment]
新增一个功能请求
给`setValue`加一个保留原有的首尾空白字符的参数
以 `{{信息模板\n|  声优 = A \n| 生日 = B \n}}'` 中的`声优`参数为例。由于无法得知前后分别有什么空白字符，对它setValue会导致后面的换行符丢失，导致源代码排版不美观。

或者`getValue`有办法得到有首尾空白字符的value也可以，然后`parser.setValue(value.replace(value.trim(), newValue))`

```typescript

getValue(noTrim: Boolean = false): string {
	const value = this.lastChild.text();
	return (noTrim || this.anon && this.parentNode?.isTemplate() !== false) ? value : value.trim();
}

```

**Comment by bhsd-harry** [comment]
> ```ts
> getValue(noTrim: Boolean = false): string {
> 	const value = this.lastChild.text();
> 	return (noTrim || this.anon && this.parentNode?.isTemplate() !== false) ? value : value.trim();
> }
> ```

这个建议直接使用`parameter.lastChild.text()`

**Comment by bhsd-harry** [comment]
@lovelyCARDINAL 请问这个issue我可以认为解决了吗？

**Comment by lovelyCARDINAL** [comment]
> @lovelyCARDINAL 请问这个issue我可以认为解决了吗？

应该可以吧，看上去没问题了，要不要发个正式版本？

**Comment by bhsd-harry** [comment]
新功能 `AstRange` 的用例见 lovelyCARDINAL/WikiBots#53
